name: wf-cd-production
on:
  push:
    branches:
      - production
jobs:
  wf-cd-build-production-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{github.ref}}
      - name: Build Artifact
        run: |
          npx parcel build "./src/index.html" --dist-dir "./dist" --public-url "./"
      - name: Upload Production Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./dist"
          name: "production-artifact"

  wf-cd-deploy-production-jobs:
    needs: wf-cd-build-production-jobs
    environment: "production-env"
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Production Artifact
        uses: actions/deploy-pages@v4
        with:
          artifact_name: "production-artifact"
          token: ${{github.token}}